"""empty message

Revision ID: bee02a0b00fb
Revises: 11e31e4ca8e8
Create Date: 2019-05-07 19:04:43.100248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee02a0b00fb'
down_revision = '11e31e4ca8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('display_name', sa.Text(), server_default='New Machine', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'display_name')
    # ### end Alembic commands ###
