"""empty message

Revision ID: c2e582eabe08
Revises: bee02a0b00fb
Create Date: 2020-02-18 18:26:42.092569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e582eabe08'
down_revision = 'bee02a0b00fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'count')
    # ### end Alembic commands ###
