"""empty message

Revision ID: cb7dfa2d53e9
Revises: f6f1ee4fab78
Create Date: 2019-05-07 17:57:44.309409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7dfa2d53e9'
down_revision = 'f6f1ee4fab78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('active', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'active')
    # ### end Alembic commands ###
