"""empty message

Revision ID: f6f1ee4fab78
Revises: 
Create Date: 2019-02-17 03:59:59.462951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f1ee4fab78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['items.id'], ),
    sa.ForeignKeyConstraint(['machine'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('machine', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['items.id'], ),
    sa.ForeignKeyConstraint(['machine'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('machine', 'number')
    )
    op.create_table('temps',
    sa.Column('machine', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['machine'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('machine', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temps')
    op.drop_table('slots')
    op.drop_table('logs')
    op.drop_table('machines')
    op.drop_table('items')
    # ### end Alembic commands ###
